// Generated by `npm run x-drafts:snapshot` from lib/x-drafts/sources.ts. Do not edit by hand.
import type { XDraftSource } from "./sources";

export const X_DRAFT_SOURCE_SNAPSHOT: readonly XDraftSource[] = [
  {
    id: "science:how-to-read-a-coa",
    kind: "evidence",
    title: "How to read a Certificate of Analysis",
    url: "https://www.psllabs.org/science/how-to-read-a-coa",
    origin: "content/science/how-to-read-a-coa.mdx (selected verbatim passages)",
    text: "A Certificate of Analysis (COA) is an original laboratory report for a **specific sample and batch**. It is not a marketing summary. Results apply only to the tested sample identified in that report.\n\n## Locate the lot number\n\n1. Find the lot or batch identifier on your vial label or packaging.\n2. On psllabs.org, open the product page for your material or go to **COA / Batch Lookup** (`/coa`).\n3. Match your label identifier to a published report. If no report is listed for your lot, contact support@psllabs.org with your lot number.\n\n## Open the original report\n\nPublished PSL reports are linked from:\n\n- The product page under **Testing & Quality**\n- **COA / Batch Lookup** (`/coa`)\n- The **Testing** section when a report is available\n\nOpen the linked image or PDF—the **original laboratory report**, not a retyped summary.\n\n[…]\n\n## Read the fields on the report\n\nReview only the fields that appear on **your** report.\n\n[…]\n\nDo not assume a field is present unless it appears on the original report you are reviewing.\n\n## Scope of results\n\nLaboratory results apply **only** to the tested sample and batch named in that report. They do not apply to other lots, future batches, or materials you have not received.\n\nTesting scope and results are shown on each original laboratory report. PSL does not add tests or results beyond what the laboratory documented on that report.\n\n[…]",
  },
  {
    id: "science:third-party-testing-explained",
    kind: "evidence",
    title: "How to verify an original laboratory report",
    url: "https://www.psllabs.org/science/third-party-testing-explained",
    origin: "content/science/third-party-testing-explained.mdx (selected verbatim passages)",
    text: "Published PSL batch documentation is the **original third-party laboratory report** for a specific sample—not a pass/fail badge or in-house summary.\n\n## What “original report” means\n\n- Issued by a laboratory independent of PSL\n- Tied to a named batch, task number, and sample\n- Shown as the laboratory's document (image or PDF), linked from PSL pages\n\nIn-house or supplier-only paperwork is not the same as a published third-party report.\n\n## Find your report on PSL\n\n1. Note the lot or batch on your vial label.\n2. Visit the product page or **COA / Batch Lookup** (`/coa`).\n3. Search by task number or batch name when lookup is available.\n4. Open the linked report and confirm the batch and task number match your label.\n\nIf no report is published for your lot, contact support@psllabs.org.\n\n## Verify with the testing laboratory\n\nWhen the report includes a verification URL or key (Janoshik reports include a verification key on the document):\n\n1. Open the original report from PSL.\n2. Follow the laboratory's verification instructions on that report.\n3. Enter the key exactly as printed on the **original** document.\n\nVerification confirms the report file matches the laboratory's records. It does not extend results to other lots.\n\n## What to record\n\n[…]\n\nTesting scope and results are shown on each original laboratory report. Review the report itself for the complete scope of testing performed.\n\n## Results apply only to the tested batch\n\nA report documents one tested sample. It does not describe other lots, future production, or materials not identified in that report.\n\n[…]",
  },
  {
    id: "statement:testing-scope",
    kind: "evidence",
    title: "Testing-scope statement",
    url: null,
    origin: "lib/content/testing-scope.ts#TESTING_SCOPE_STATEMENT",
    text: "The report only covers the tests shown on the original laboratory file.",
  },
  {
    id: "guidance:claims-rules",
    kind: "guidance",
    title: "claims-rules",
    url: null,
    origin: "ops-knowledge/compliance/claims-rules.md (## Research-use / FDA framing (live); ## Testing-scope claim limit (live))",
    text: "## Research-use / FDA framing (live)\n\nSources: `lib/content/disclaimer.ts`, `lib/content/testing-scope.ts`, `lib/content/terms.ts`.\n\n- Products are sold **strictly for laboratory and research use only**.\n- Not intended for human or animal consumption, diagnosis, treatment, cure, or prevention of any disease.\n- Product descriptions, testing summaries, and COAs support research documentation — they are not medical advice or usage guidance.\n- Standard FDA disclaimer language is published on the disclaimer page:\n  > These statements have not been evaluated by the Food and Drug Administration. This product is not intended to diagnose, treat, cure, or prevent any disease.\n\n## Testing-scope claim limit (live)\n\nSource: `lib/content/testing-scope.ts`.\n\n- Canonical statement: **“The report only covers the tests shown on the original laboratory file.”**\n- Do not overstate lab methods or results beyond the published report.",
  },
  {
    id: "guidance:prohibited-content",
    kind: "guidance",
    title: "prohibited-content",
    url: null,
    origin: "ops-knowledge/compliance/prohibited-content.md (## Never in public / agent / support replies (live); ## Unsafe marketing claims listed in `claims.md`)",
    text: "## Never in public / agent / support replies (live)\n\nSources: `lib/content/disclaimer.ts`, `lib/content/site-faq.ts`, `lib/support/knowledge.ts`, `lib/fulfillment/packing-slip.ts`, email legal footers.\n\n- Human or animal consumption / administration guidance.\n- Dosing, injection, reconstitution for personal use, treatment, or medical guidance.\n- Presenting COAs or product copy as medical advice.\n\n## Unsafe marketing claims listed in `claims.md`\n\nSource: `claims.md` (treat as prohibited unless Luke re-approves otherwise):\n\n- “Treats / cures / prevents / heals [anything]”\n- “Anti-aging” as a verb claim (“anti-aging supplement”)\n- “Boosts” / “increases” specific biomarkers without substantiation\n- “Clinically proven” unless the product itself has clinical studies\n- “Doctor recommended” without signed endorsement + substantiation file\n- Weight loss claims of any kind\n- “Replaces” or “alternative to” any prescription medication\n- “Natural Ozempic,” “natural GLP-1,” or drug comparisons\n- Before/after photography\n- Specific outcome claims (“you will…”)",
  },
];
