import fs from "node:fs";
import path from "node:path";

import matter from "gray-matter";

import { ANALYTICAL_GUIDES } from "@/lib/content/guides-data";
import { TESTING_SCOPE_STATEMENT } from "@/lib/content/testing-scope";

import { X_DRAFT_SOURCE_ALLOWLIST, type XDraftSource, type XDraftSourceSpec } from "./sources";

/**
 * Reads the allowlisted sources from the working tree. Used only by the
 * snapshot script and tests; the endpoints serve the committed snapshot.
 */
function read(root: string, file: string): string {
  return fs.readFileSync(path.join(root, file), "utf8").replace(/\r\n?/g, "\n");
}

function sections(markdown: string, headings: readonly string[], file: string): string {
  const { content } = matter(markdown);
  const blocks = content.split(/\n(?=## )/);
  return headings
    .map((heading) => {
      const block = blocks.find((b) => b.trimStart().startsWith(`## ${heading}\n`));
      if (!block) throw new Error(`${file}: section "## ${heading}" not found`);
      return block.trim();
    })
    .join("\n\n");
}

function build(spec: XDraftSourceSpec, root: string): XDraftSource {
  const s = spec.select;
  switch (s.type) {
    case "mdx-article": {
      const { data, content } = matter(read(root, s.file));
      const title = String(data.title ?? "").trim();
      const description = String(data.description ?? "").trim();
      if (!title || !description) throw new Error(`${s.file}: title and description are required`);
      return { id: spec.id, kind: spec.kind, title, url: spec.url, origin: s.file, text: `${title}\n\n${description}\n\n${content.trim()}` };
    }
    case "guide-meta": {
      const guide = ANALYTICAL_GUIDES.find((g) => g.slug === s.slug);
      if (!guide) throw new Error(`guide ${s.slug} not found in lib/content/guides-data.ts`);
      return {
        id: spec.id,
        kind: spec.kind,
        title: guide.title,
        url: spec.url,
        origin: `lib/content/guides-data.ts#${s.slug}`,
        text: `${guide.title}\n\n${guide.description}`,
      };
    }
    case "constant":
      return {
        id: spec.id,
        kind: spec.kind,
        title: "Testing-scope statement",
        url: spec.url,
        origin: `${s.module}#${s.name}`,
        text: TESTING_SCOPE_STATEMENT,
      };
    case "md-sections": {
      const raw = read(root, s.file);
      const { data } = matter(raw);
      if (data.status !== "approved") throw new Error(`${s.file}: guidance must have status: approved`);
      return {
        id: spec.id,
        kind: spec.kind,
        title: path.basename(s.file, ".md"),
        url: spec.url,
        origin: `${s.file} (${s.headings.map((h) => `## ${h}`).join("; ")})`,
        text: sections(raw, s.headings, s.file),
      };
    }
  }
}

export function buildXDraftSources(root = process.cwd()): XDraftSource[] {
  const ids = new Set<string>();
  return X_DRAFT_SOURCE_ALLOWLIST.map((spec) => {
    if (ids.has(spec.id)) throw new Error(`duplicate source id ${spec.id}`);
    ids.add(spec.id);
    return build(spec, root);
  });
}

export function renderXDraftSnapshotModule(sources: XDraftSource[]): string {
  const body = sources
    .map(
      (s) =>
        `  {\n    id: ${JSON.stringify(s.id)},\n    kind: ${JSON.stringify(s.kind)},\n    title: ${JSON.stringify(s.title)},\n    url: ${JSON.stringify(s.url)},\n    origin: ${JSON.stringify(s.origin)},\n    text: ${JSON.stringify(s.text)},\n  },`
    )
    .join("\n");
  return [
    "// Generated by `npm run x-drafts:snapshot` from lib/x-drafts/sources.ts. Do not edit by hand.",
    'import type { XDraftSource } from "./sources";',
    "",
    "export const X_DRAFT_SOURCE_SNAPSHOT: readonly XDraftSource[] = [",
    body,
    "];",
    "",
  ].join("\n");
}
